version: "3.8"

x-defaults: &defaults
  init: true
  tty: true

services:
  database:
    <<: *defaults
    image: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: database_pgdata
